import Foundation

// MARK: - Plan Day

/// Which day the user is planning for.
enum PlanDay: Equatable, CaseIterable {
    case today
    case tomorrow
    case saturday
    case sunday

    /// The actual calendar date for this plan day.
    func date() -> Date {
        let cal = Calendar.current
        let now = Date()
        switch self {
        case .today: return now
        case .tomorrow:
            return cal.date(byAdding: .day, value: 1, to: now) ?? now
        case .saturday:
            return PlanDay.nextWeekendDates().saturday
        case .sunday:
            return PlanDay.nextWeekendDates().sunday
        }
    }

    /// ISO date string for API calls.
    var isoDate: String {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd"
        f.timeZone = TimeZone(identifier: "Europe/Zurich")
        return f.string(from: date())
    }

    /// Short label like "Sat 15" for day picker pills.
    func shortLabel(language: AppLanguage) -> String {
        let f = DateFormatter()
        f.locale = language == .de ? Locale(identifier: "de_CH") : Locale(identifier: "en_US")
        f.dateFormat = language == .de ? "EE d." : "EEE d"
        return f.string(from: date())
    }

    /// Display name for headers.
    func headerTitle(language: AppLanguage) -> String {
        switch self {
        case .today:
            return language == .en ? "Your day" : "Dein Tag"
        case .tomorrow:
            return language == .en ? "Tomorrow's plan" : "Plan für morgen"
        case .saturday, .sunday:
            return language == .en ? "Weekend plan" : "Wochenendplan"
        }
    }

    /// Get next Saturday and Sunday dates.
    static func nextWeekendDates() -> (saturday: Date, sunday: Date) {
        let cal = Calendar.current
        let now = Date()
        let weekday = cal.component(.weekday, from: now) // 1=Sun, 7=Sat

        let daysToSat: Int
        switch weekday {
        case 7: daysToSat = 0  // Already Saturday
        case 1: daysToSat = 6  // Sunday → next Saturday
        default: daysToSat = 7 - weekday
        }

        let saturday = cal.date(byAdding: .day, value: daysToSat, to: now) ?? now
        let sunday = cal.date(byAdding: .day, value: 1, to: saturday) ?? now
        return (saturday, sunday)
    }

    static var allCases: [PlanDay] { [.today, .tomorrow, .saturday, .sunday] }
}

// MARK: - Agenda Mode

/// Execution state for the day agenda.
enum AgendaMode: Codable, Equatable {
    case browsing
    case executing(currentSlotIndex: Int)

    /// The index of the currently active slot, or nil if browsing.
    var currentSlotIndex: Int? {
        if case .executing(let idx) = self { return idx }
        return nil
    }

    /// Whether we're in execution mode.
    var isExecuting: Bool {
        if case .executing = self { return true }
        return false
    }

    /// Number of completed slots (all before currentSlotIndex).
    func completedCount(totalSlots: Int) -> Int {
        guard let idx = currentSlotIndex else { return 0 }
        return min(idx, totalSlots)
    }
}

// MARK: - Slot Source

/// Origin of a slot's content.
enum SlotSource: String, Codable {
    case aiGenerated    // Claude composed this
    case userCustom     // user entered manually
    case userSwapped    // user picked from swap tray
    case userAnchor     // pre-existing commitment entered before compose
}

// MARK: - Day Agenda

/// A complete day agenda generated by the Agenda Composer.
struct DayAgenda: Codable {
    let date: String                    // ISO date "2026-03-14"
    let theme: String                   // e.g. "Sunny Saturday with Mia"
    let weatherNote: String             // e.g. "14° and partly sunny"
    let badWeatherMode: Bool
    var slots: [AgendaSlot]
    let homeActivities: HomeActivities?

    /// Whether any slot has a pending reflow (stale downstream slots).
    var hasStaleSlots: Bool {
        slots.contains { $0.isStale }
    }

    /// Return a copy with replaced slots array.
    func with(slots newSlots: [AgendaSlot]) -> DayAgenda {
        var copy = self
        copy.slots = newSlots
        return copy
    }
}

/// Forecasted weather at a specific slot's time.
struct SlotWeather: Codable {
    let temp: Int           // °C from hourly forecast
    let code: Int           // WMO weather code
    let rain: Bool          // whether rain is expected

    /// SF Symbol for the WMO weather code.
    var sfSymbol: String {
        switch code {
        case 0: return "sun.max.fill"
        case 1: return "sun.max.fill"
        case 2: return "cloud.sun.fill"
        case 3: return "cloud.fill"
        case 45, 48: return "cloud.fog.fill"
        case 51, 53, 55: return "cloud.drizzle.fill"
        case 56, 57: return "cloud.sleet.fill"
        case 61, 63, 65: return "cloud.rain.fill"
        case 66, 67: return "cloud.sleet.fill"
        case 71, 73, 75, 77: return "cloud.snow.fill"
        case 80, 81, 82: return "cloud.heavyrain.fill"
        case 85, 86: return "cloud.snow.fill"
        case 95, 96, 99: return "cloud.bolt.rain.fill"
        default: return "cloud.fill"
        }
    }
}

/// One time slot in the day's agenda.
struct AgendaSlot: Codable, Identifiable {
    let id: String                      // "morning", "lunch", "afternoon", "dinner"
    var time: String                    // "10:00"
    let type: SlotType
    var venueName: String
    var venueId: String?
    var reason: String                  // Claude's 1-2 sentence reasoning
    let durationDisplay: String?
    var travelNote: String?             // "8 min walk from home"
    let tags: [String]                  // ["Outdoor", "Free", "Ages 2-5"]
    let swaps: [SwapOption]
    var travelMinutesToNext: Int?       // Travel time to the next slot
    var weatherAtSlot: SlotWeather?     // Forecasted weather at this slot's time

    // MARK: - Check-In Tracking

    /// Actual arrival time (set when user taps Done or geofence fires).
    var checkInTime: Date?

    /// Actual departure time (set on geofence exit, if available).
    var checkOutTime: Date?

    /// True if geofence triggered, false if manual Done tap.
    var wasAutoCheckedIn: Bool

    // MARK: - Custom Slot / Lock

    /// Origin of this slot's content.
    var source: SlotSource

    /// When true, this slot is never replaced by reflow.
    var isLocked: Bool

    /// Custom venue name (only set when source == .userCustom).
    var customVenueName: String?

    /// Custom neighbourhood (used for travel connector logic when source == .userCustom).
    var customNeighbourhood: String?

    /// Whether downstream AI slots are stale after an upstream custom edit.
    var isStale: Bool

    // MARK: - Computed Date

    /// Full Date combining today's date with the slot's "HH:mm" time string.
    /// Used by TimelineShifter and notification scheduling.
    var slotDate: Date {
        let parts = time.split(separator: ":").compactMap { Int($0) }
        guard parts.count == 2 else { return Date() }
        var cal = Calendar.current
        cal.timeZone = .current
        let today = cal.startOfDay(for: Date())
        return cal.date(bySettingHour: parts[0], minute: parts[1], second: 0, of: today) ?? Date()
    }

    /// Update the time string from a Date.
    mutating func updateTime(from date: Date) {
        let f = DateFormatter()
        f.dateFormat = "HH:mm"
        time = f.string(from: date)
    }

    enum SlotType: String, Codable {
        case activity
        case lunch
        case dinner
        case homeActivity
    }

    struct SwapOption: Codable, Identifiable {
        let id: String
        let venueName: String
        let detail: String              // "Free · 12 min walk"
        let venueId: String?
    }

    enum CodingKeys: String, CodingKey {
        case id, time, type, venueName, venueId, reason, durationDisplay
        case travelNote, tags, swaps, travelMinutesToNext, weatherAtSlot
        case checkInTime, checkOutTime, wasAutoCheckedIn
        case source, isLocked, customVenueName, customNeighbourhood, isStale
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        time = try container.decode(String.self, forKey: .time)
        type = try container.decode(SlotType.self, forKey: .type)
        venueName = try container.decode(String.self, forKey: .venueName)
        venueId = try container.decodeIfPresent(String.self, forKey: .venueId)
        reason = try container.decode(String.self, forKey: .reason)
        durationDisplay = try container.decodeIfPresent(String.self, forKey: .durationDisplay)
        travelNote = try container.decodeIfPresent(String.self, forKey: .travelNote)
        tags = try container.decode([String].self, forKey: .tags)
        swaps = try container.decode([SwapOption].self, forKey: .swaps)
        travelMinutesToNext = try container.decodeIfPresent(Int.self, forKey: .travelMinutesToNext)
        weatherAtSlot = try container.decodeIfPresent(SlotWeather.self, forKey: .weatherAtSlot)
        // Check-in fields with defaults for backward compatibility
        checkInTime = try container.decodeIfPresent(Date.self, forKey: .checkInTime)
        checkOutTime = try container.decodeIfPresent(Date.self, forKey: .checkOutTime)
        wasAutoCheckedIn = try container.decodeIfPresent(Bool.self, forKey: .wasAutoCheckedIn) ?? false
        // New fields with defaults for backward compatibility
        source = try container.decodeIfPresent(SlotSource.self, forKey: .source) ?? .aiGenerated
        isLocked = try container.decodeIfPresent(Bool.self, forKey: .isLocked) ?? false
        customVenueName = try container.decodeIfPresent(String.self, forKey: .customVenueName)
        customNeighbourhood = try container.decodeIfPresent(String.self, forKey: .customNeighbourhood)
        isStale = try container.decodeIfPresent(Bool.self, forKey: .isStale) ?? false
    }

    init(
        id: String, time: String, type: SlotType, venueName: String, venueId: String?,
        reason: String, durationDisplay: String? = nil, travelNote: String? = nil,
        tags: [String], swaps: [SwapOption], travelMinutesToNext: Int? = nil,
        weatherAtSlot: SlotWeather? = nil,
        checkInTime: Date? = nil, checkOutTime: Date? = nil, wasAutoCheckedIn: Bool = false,
        source: SlotSource = .aiGenerated, isLocked: Bool = false,
        customVenueName: String? = nil, customNeighbourhood: String? = nil,
        isStale: Bool = false
    ) {
        self.id = id
        self.time = time
        self.type = type
        self.venueName = venueName
        self.venueId = venueId
        self.reason = reason
        self.durationDisplay = durationDisplay
        self.travelNote = travelNote
        self.tags = tags
        self.swaps = swaps
        self.travelMinutesToNext = travelMinutesToNext
        self.weatherAtSlot = weatherAtSlot
        self.checkInTime = checkInTime
        self.checkOutTime = checkOutTime
        self.wasAutoCheckedIn = wasAutoCheckedIn
        self.source = source
        self.isLocked = isLocked
        self.customVenueName = customVenueName
        self.customNeighbourhood = customNeighbourhood
        self.isStale = isStale
    }
}

/// Home activities for bad weather days.
struct HomeActivities: Codable {
    let baking: HomeActivity?
    let movie: MoviePick?
    let craft: HomeActivity?
}

struct HomeActivity: Codable, Identifiable {
    var id: String { idea }
    let label: String                   // "MORNING · BAKING" / "CRAFT"
    let idea: String                    // "Bürli rolls together"
    let emoji: String                   // "🥐"
    let reason: String                  // why this fits
    let durationDisplay: String         // "~45 min active"
    let ageNote: String?                // "Ages 4+"
}

struct MoviePick: Codable, Identifiable {
    var id: String { title }
    let label: String                   // "AFTER LUNCH · SCREEN TIME"
    let title: String                   // "Pippi Longstocking (1969)"
    let emoji: String                   // "🎬"
    let reason: String                  // "Age-perfect for both kids"
    let platform: String?               // "SRF Play Kids"
    let durationMinutes: Int            // 99
    let isFree: Bool
}
