/**
 * Events — City events/festivals for 2026.
 */

export const VERSION = '2.0.0';

const ALL_EVENTS = [
  // ═══ ZÜRICH ═══
  { id: 'zh-fasnacht', name: 'Züri Carneval', nameDE: 'Züri Carneval', city: 'zurich', startDate: '2026-02-20', endDate: '2026-02-22', description: "Zurich's carnival with costumes, confetti, Guggenmusik.", descriptionDE: 'Zürcher Karneval mit Kostümen, Konfetti, Guggenmusik.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-zwaenzgerle', name: 'Zwänzgerle', nameDE: 'Zwänzgerle', city: 'zurich', startDate: '2026-04-06', endDate: '2026-04-06', description: 'Easter Monday tradition — kids try to crack eggs while adults toss coins.', descriptionDE: 'Ostermontag-Tradition — Kinder halten Eier hin, Erwachsene werfen Münzen.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-marathon', name: 'Zurich Marathon', nameDE: 'Zürich Marathon', city: 'zurich', startDate: '2026-04-12', endDate: '2026-04-12', description: 'Annual marathon — great spectator event for kids.', descriptionDE: 'Jährlicher Marathon — tolles Zuschauevent für Kinder.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-sechselaeuten', name: 'Sechseläuten', nameDE: 'Sechseläuten', city: 'zurich', startDate: '2026-04-20', endDate: '2026-04-20', description: "Zurich's spring festival — children's parade and Böögg burning.", descriptionDE: 'Zürcher Frühlingsfest — Kinderumzug und Böögg-Verbrennung.', toddlerFriendly: true, free: true, url: 'https://www.sechselaeuten.ch/' },
  { id: 'zh-zueritanzt', name: 'Zürich Tanzt', nameDE: 'Zürich Tanzt', city: 'zurich', startDate: '2026-05-07', endDate: '2026-05-10', description: 'Dance festival with performances across the city.', descriptionDE: 'Tanzfestival mit Aufführungen in der ganzen Stadt.', toddlerFriendly: false, free: true, url: '' },
  { id: 'zh-circus-knie', name: 'Circus Knie Zürich', nameDE: 'Circus Knie Zürich', city: 'zurich', startDate: '2026-05-14', endDate: '2026-06-07', description: "Switzerland's national circus with acrobatics, clowns and animals.", descriptionDE: 'Schweizer Nationalzirkus mit Akrobatik, Clowns und Tieren.', toddlerFriendly: true, free: false, url: 'https://www.knie.ch/' },
  { id: 'zh-kreislauf345', name: 'Kreislauf 345', nameDE: 'Kreislauf 345', city: 'zurich', startDate: '2026-05-30', endDate: '2026-05-31', description: '80 shops open in districts 3, 4, and 5 — family-friendly strolling.', descriptionDE: '80 Shops öffnen in den Kreisen 3, 4 und 5 — familienfreundliches Flanieren.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-pride', name: 'Zurich Pride Festival', nameDE: 'Zurich Pride Festival', city: 'zurich', startDate: '2026-06-19', endDate: '2026-06-20', description: 'Colorful LGBTQ+ celebration with parade.', descriptionDE: 'Buntes LGBTQ+-Fest mit Parade.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-openair-wipkingen', name: 'Openair Wipkingen', nameDE: 'Openair Wipkingen', city: 'zurich', startDate: '2026-06-13', endDate: '2026-06-13', description: 'Free neighbourhood festival by the Limmat.', descriptionDE: 'Gratis Quartiersfest an der Limmat.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-opera-for-all', name: 'Oper für alle', nameDE: 'Oper für alle', city: 'zurich', startDate: '2026-06-26', endDate: '2026-06-28', description: 'Free opera screening on Sechseläutenplatz.', descriptionDE: 'Gratis Opernübertragung auf dem Sechseläutenplatz.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-caliente', name: 'Caliente!', nameDE: 'Caliente!', city: 'zurich', startDate: '2026-07-03', endDate: '2026-07-05', description: "Europe's largest Latin music festival at Hauptbahnhof.", descriptionDE: 'Europas grösstes lateinamerikanisches Musikfestival am HB.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-allianz-cinema', name: 'Allianz Cinema', nameDE: 'Allianz Cinema', city: 'zurich', startDate: '2026-07-16', endDate: '2026-08-16', description: 'Open-air cinema on Lake Zurich.', descriptionDE: 'Open-Air-Kino am Zürichsee.', toddlerFriendly: false, free: false, url: '' },
  { id: 'zh-langstrassenfest', name: 'Langstrassenfest', nameDE: 'Langstrassenfest', city: 'zurich', startDate: '2026-07-04', endDate: '2026-07-04', description: 'Street festival on Langstrasse (Kreis 4/5).', descriptionDE: 'Strassenfest an der Langstrasse (Kreis 4/5).', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-street-parade', name: 'Street Parade', nameDE: 'Street Parade', city: 'zurich', startDate: '2026-08-08', endDate: '2026-08-08', description: "World's largest techno parade. Very loud.", descriptionDE: 'Grösste Technoparade der Welt. Sehr laut.', toddlerFriendly: false, free: true, url: '' },
  { id: 'zh-theater-spektakel', name: 'Theater Spektakel', nameDE: 'Theater Spektakel', city: 'zurich', startDate: '2026-08-13', endDate: '2026-08-30', description: 'International performing arts festival on the lake.', descriptionDE: 'Internationales Theaterfestival am See.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-idaplatzfest', name: 'Idaplatzfest', nameDE: 'Idaplatzfest', city: 'zurich', startDate: '2026-08-15', endDate: '2026-08-15', description: 'Beloved Kreis 3 neighbourhood festival.', descriptionDE: 'Beliebtes Kreis-3-Quartiersfest.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-roentgenplatzfest', name: 'Röntgenplatzfest', nameDE: 'Röntgenplatzfest', city: 'zurich', startDate: '2026-08-22', endDate: '2026-08-22', description: 'Neighbourhood festival on Röntgenplatz (Kreis 5).', descriptionDE: 'Quartiersfest am Röntgenplatz (Kreis 5).', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-lichterschwimmen', name: 'Lichterschwimmen', nameDE: 'Lichterschwimmen', city: 'zurich', startDate: '2026-08-22', endDate: '2026-08-22', description: 'Floating candles on the Limmat — magical spectacle.', descriptionDE: 'Schwimmende Kerzen auf der Limmat — magisches Spektakel.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-lindenplatzfest', name: 'Lindenplatzfest', nameDE: 'Lindenplatzfest', city: 'zurich', startDate: '2026-08-29', endDate: '2026-08-29', description: 'Neighbourhood festival on Lindenplatz (Kreis 4).', descriptionDE: 'Quartiersfest am Lindenplatz (Kreis 4).', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-doerflifaescht', name: 'Dörflifäscht', nameDE: 'Dörflifäscht', city: 'zurich', startDate: '2026-08-28', endDate: '2026-08-30', description: 'Old town Niederdorf transforms into a festival.', descriptionDE: 'Die Altstadt Niederdorf verwandelt sich in ein Fest.', toddlerFriendly: true, free: true, url: 'https://doerflifaescht.ch/' },
  { id: 'zh-zurich-openair', name: 'Zürich Openair', nameDE: 'Zürich Openair', city: 'zurich', startDate: '2026-08-28', endDate: '2026-09-05', description: 'Music festival with international acts near the airport.', descriptionDE: 'Musikfestival mit internationalen Acts beim Flughafen.', toddlerFriendly: false, free: false, url: '' },
  { id: 'zh-weltklasse', name: 'Weltklasse Zürich', nameDE: 'Weltklasse Zürich', city: 'zurich', startDate: '2026-08-26', endDate: '2026-08-27', description: 'World-class athletics meeting at Letzigrund.', descriptionDE: 'Weltklasse-Leichtathletik-Meeting im Letzigrund.', toddlerFriendly: true, free: false, url: '' },
  { id: 'zh-lange-nacht', name: 'Lange Nacht der Museen', nameDE: 'Lange Nacht der Museen', city: 'zurich', startDate: '2026-09-05', endDate: '2026-09-05', description: 'Night of museums with special programs.', descriptionDE: 'Museumsnacht mit speziellen Programmen.', toddlerFriendly: true, free: false, url: '' },
  { id: 'zh-food-zurich', name: 'FOOD ZURICH', nameDE: 'FOOD ZURICH', city: 'zurich', startDate: '2026-09-03', endDate: '2026-09-13', description: "Zurich's food festival with tastings and workshops.", descriptionDE: 'Zürichs Food-Festival mit Degustationen und Workshops.', toddlerFriendly: true, free: false, url: '' },
  { id: 'zh-knabenschiessen', name: 'Knabenschiessen', nameDE: 'Knabenschiessen', city: 'zurich', startDate: '2026-09-12', endDate: '2026-09-14', description: "Zurich's biggest folk festival with fun fair.", descriptionDE: 'Zürichs grösstes Volksfest mit Chilbi.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-zff', name: 'Zurich Film Festival', nameDE: 'Zurich Film Festival', city: 'zurich', startDate: '2026-09-24', endDate: '2026-10-04', description: 'International film festival with premieres.', descriptionDE: 'Internationales Filmfestival mit Premieren.', toddlerFriendly: false, free: false, url: '' },
  { id: 'zh-expovina', name: 'Expovina', nameDE: 'Expovina', city: 'zurich', startDate: '2026-10-29', endDate: '2026-11-12', description: 'Wine exhibition aboard boats on Lake Zurich.', descriptionDE: 'Weinausstellung auf Schiffen am Zürichsee.', toddlerFriendly: false, free: false, url: '' },
  { id: 'zh-hoengger-wuemmet', name: 'Höngger Wümmet', nameDE: 'Höngger Wümmet', city: 'zurich', startDate: '2026-10-03', endDate: '2026-10-03', description: 'Wine harvest festival in Höngg (Kreis 10).', descriptionDE: 'Weinfest in Höngg (Kreis 10).', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-raebeliechtli', name: 'Räbeliechtli-Umzug', nameDE: 'Räbeliechtli-Umzug', city: 'zurich', startDate: '2026-11-07', endDate: '2026-11-07', description: 'Magical turnip lantern parade — beloved children tradition.', descriptionDE: 'Magischer Räbeliechtli-Umzug — beliebte Kindertradition.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-christmas', name: 'Christmas Markets Zurich', nameDE: 'Weihnachtsmärkte Zürich', city: 'zurich', startDate: '2026-11-19', endDate: '2026-12-23', description: 'Multiple Christmas markets including HB, Bellevue, Niederdorf.', descriptionDE: 'Mehrere Weihnachtsmärkte inkl. HB, Bellevue und Niederdorf.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-maerlitram', name: 'Märlitram', nameDE: 'Märlitram', city: 'zurich', startDate: '2026-11-25', endDate: '2026-12-23', description: 'Fairy tale tram rides through Christmas Zurich.', descriptionDE: 'Märchentram-Fahrten durch das weihnachtliche Zürich.', toddlerFriendly: true, free: false, url: '' },
  { id: 'zh-silvesterlauf', name: 'Zürcher Silvesterlauf', nameDE: 'Zürcher Silvesterlauf', city: 'zurich', startDate: '2026-12-13', endDate: '2026-12-13', description: 'Festive running event through the city.', descriptionDE: 'Festlicher Lauf durch die Stadt.', toddlerFriendly: true, free: true, url: '' },
  { id: 'zh-silvesterzauber', name: 'Silvesterzauber', nameDE: 'Silvesterzauber', city: 'zurich', startDate: '2026-12-31', endDate: '2026-12-31', description: "New Year's Eve at the lake with fireworks.", descriptionDE: 'Silvesterfeier am See mit Feuerwerk.', toddlerFriendly: false, free: true, url: '' },

  // ═══ BASEL ═══
  { id: 'bs-vogel-gryff', name: 'Vogel Gryff', nameDE: 'Vogel Gryff', city: 'basel', startDate: '2026-01-27', endDate: '2026-01-27', description: "Basel's traditional folk festival in Kleinbasel.", descriptionDE: 'Basler Volksfest in Kleinbasel.', toddlerFriendly: true, free: true, url: '' },
  { id: 'bs-fasnacht', name: 'Basler Fasnacht', nameDE: 'Basler Fasnacht', city: 'basel', startDate: '2026-02-23', endDate: '2026-02-25', description: 'UNESCO world heritage carnival — Morgestraich at 4am.', descriptionDE: 'UNESCO-Weltkulturerbe Fasnacht — Morgestraich um 4 Uhr.', toddlerFriendly: true, free: true, url: '' },
  { id: 'bs-imagine', name: 'IMAGINE Festival', nameDE: 'IMAGINE Festival', city: 'basel', startDate: '2026-05-22', endDate: '2026-05-23', description: 'Free music festival promoting diversity.', descriptionDE: 'Gratis Musikfestival für Vielfalt.', toddlerFriendly: true, free: true, url: '' },
  { id: 'bs-art-basel', name: 'Art Basel', nameDE: 'Art Basel', city: 'basel', startDate: '2026-06-18', endDate: '2026-06-21', description: "World's premier modern art fair.", descriptionDE: 'Weltweit führende Kunstmesse.', toddlerFriendly: false, free: false, url: 'https://www.artbasel.com/' },
  { id: 'bs-tattoo', name: 'Basel Tattoo', nameDE: 'Basel Tattoo', city: 'basel', startDate: '2026-07-17', endDate: '2026-07-25', description: 'International military music festival.', descriptionDE: 'Internationales Militärmusik-Festival.', toddlerFriendly: false, free: false, url: '' },
  { id: 'bs-floss', name: 'FLOSS Festival', nameDE: 'FLOSS Festival', city: 'basel', startDate: '2026-08-14', endDate: '2026-08-15', description: 'Open-air music and culture festival on the Rhine.', descriptionDE: 'Open-Air Musik- und Kulturfestival am Rhein.', toddlerFriendly: true, free: true, url: '' },
  { id: 'bs-em-bebbi', name: 'Em Bebbi sy Jazz', nameDE: 'Em Bebbi sy Jazz', city: 'basel', startDate: '2026-08-29', endDate: '2026-08-29', description: "Free jazz festival throughout Basel's old town.", descriptionDE: 'Gratis Jazzfestival in der Basler Altstadt.', toddlerFriendly: true, free: true, url: '' },
  { id: 'bs-herbstmesse', name: 'Basler Herbstmesse', nameDE: 'Basler Herbstmesse', city: 'basel', startDate: '2026-10-24', endDate: '2026-11-08', description: "Switzerland's oldest and largest funfair.", descriptionDE: 'Älteste und grösste Chilbi der Schweiz.', toddlerFriendly: true, free: true, url: '' },
  { id: 'bs-christmas', name: 'Basel Christmas Market', nameDE: 'Basler Weihnachtsmarkt', city: 'basel', startDate: '2026-11-26', endDate: '2026-12-23', description: "One of Switzerland's most beautiful Christmas markets.", descriptionDE: 'Einer der schönsten Weihnachtsmärkte der Schweiz.', toddlerFriendly: true, free: true, url: '' },
  { id: 'bs-circus-knie', name: 'Circus Knie Basel', nameDE: 'Circus Knie Basel', city: 'basel', startDate: '2026-05-28', endDate: '2026-06-07', description: "Switzerland's national circus visits Basel.", descriptionDE: 'Schweizer Nationalzirkus gastiert in Basel.', toddlerFriendly: true, free: false, url: 'https://www.knie.ch/' },
  { id: 'bs-museumsnacht', name: 'Museumsnacht Basel', nameDE: 'Museumsnacht Basel', city: 'basel', startDate: '2026-01-16', endDate: '2026-01-16', description: 'Night of museums with special family programs.', descriptionDE: 'Museumsnacht mit Familienprogrammen.', toddlerFriendly: true, free: false, url: '' },

  // ═══ BERN ═══
  { id: 'be-fasnacht', name: 'Berner Fasnacht', nameDE: 'Berner Fasnacht', city: 'bern', startDate: '2026-02-26', endDate: '2026-02-28', description: "Bern's carnival with parade and Guggenmusik.", descriptionDE: 'Berner Fasnacht mit Umzug und Guggenmusik.', toddlerFriendly: true, free: true, url: '' },
  { id: 'be-grand-prix', name: 'Grand Prix of Bern', nameDE: 'Grand-Prix von Bern', city: 'bern', startDate: '2026-05-09', endDate: '2026-05-09', description: 'Popular 10-mile run through the old town.', descriptionDE: 'Beliebter 10-Meilen-Lauf durch die Altstadt.', toddlerFriendly: true, free: true, url: '' },
  { id: 'be-gurtenfestival', name: 'Gurtenfestival', nameDE: 'Gurtenfestival', city: 'bern', startDate: '2026-07-15', endDate: '2026-07-18', description: 'Open-air music festival on Gurten hill.', descriptionDE: 'Open-Air Musikfestival auf dem Gurten.', toddlerFriendly: true, free: false, url: '' },
  { id: 'be-buskers', name: 'Buskers Bern', nameDE: 'Buskers Bern', city: 'bern', startDate: '2026-08-06', endDate: '2026-08-08', description: 'Street music festival in the old town.', descriptionDE: 'Strassenmusik-Festival in der Altstadt.', toddlerFriendly: true, free: true, url: '' },
  { id: 'be-sichlete', name: 'Sichlete', nameDE: 'Sichlete', city: 'bern', startDate: '2026-11-23', endDate: '2026-11-23', description: 'Traditional harvest market in the Bundesgasse.', descriptionDE: 'Traditioneller Erntemarkt in der Bundesgasse.', toddlerFriendly: true, free: true, url: '' },
  { id: 'be-rendez-vous', name: 'Rendez-vous Bundesplatz', nameDE: 'Rendez-vous Bundesplatz', city: 'bern', startDate: '2026-10-15', endDate: '2026-11-22', description: 'Spectacular light show on the Federal Palace.', descriptionDE: 'Spektakuläre Lichtshow am Bundeshaus.', toddlerFriendly: true, free: true, url: '' },
  { id: 'be-zibelemarit', name: 'Zibelemärit', nameDE: 'Zibelemärit', city: 'bern', startDate: '2026-11-30', endDate: '2026-11-30', description: 'Famous onion market — confetti battles and fun.', descriptionDE: 'Berühmter Zwiebelmarkt — Konfettischlachten und Spass.', toddlerFriendly: true, free: true, url: '' },
  { id: 'be-christmas', name: 'Bern Christmas Market', nameDE: 'Berner Weihnachtsmarkt', city: 'bern', startDate: '2026-11-28', endDate: '2026-12-24', description: "Christmas market on Münsterplatz with children's program.", descriptionDE: 'Weihnachtsmarkt auf dem Münsterplatz mit Kinderprogramm.', toddlerFriendly: true, free: true, url: '' },
  { id: 'be-museumsnacht', name: 'Museumsnacht Bern', nameDE: 'Museumsnacht Bern', city: 'bern', startDate: '2026-03-20', endDate: '2026-03-20', description: 'Night of museums with family programs.', descriptionDE: 'Museumsnacht mit Familienprogrammen.', toddlerFriendly: true, free: false, url: '' },
  { id: 'be-aare-schwimmen', name: 'Aareschwimmen', nameDE: 'Aareschwimmen', city: 'bern', startDate: '2026-08-01', endDate: '2026-08-01', description: 'Mass swim in the Aare on Swiss National Day.', descriptionDE: 'Massenschwimmen in der Aare am Nationalfeiertag.', toddlerFriendly: true, free: true, url: '' },
  { id: 'be-nationalfeiertag', name: 'Swiss National Day Bern', nameDE: '1. August Feier Bern', city: 'bern', startDate: '2026-08-01', endDate: '2026-08-01', description: 'National Day celebrations with fireworks on the Gurten.', descriptionDE: '1. August Feier mit Feuerwerk auf dem Gurten.', toddlerFriendly: true, free: true, url: '' },

  // ═══ GENEVA ═══
  { id: 'ge-geneva-lux', name: 'Geneva Lux', nameDE: 'Geneva Lux', city: 'geneva', startDate: '2026-01-22', endDate: '2026-02-01', description: 'Winter light festival with illuminated art installations.', descriptionDE: 'Winter-Lichtfestival mit beleuchteten Kunstinstallationen.', toddlerFriendly: true, free: true, url: '' },
  { id: 'ge-fete-danse', name: 'Fête de la Danse', nameDE: 'Fête de la Danse', city: 'geneva', startDate: '2026-05-08', endDate: '2026-05-10', description: 'Dance festival with free workshops for all ages.', descriptionDE: 'Tanzfestival mit kostenlosen Workshops.', toddlerFriendly: true, free: true, url: '' },
  { id: 'ge-fete-musique', name: 'Fête de la Musique', nameDE: 'Fête de la Musique', city: 'geneva', startDate: '2026-06-20', endDate: '2026-06-21', description: 'Free open-air music festival all over Geneva.', descriptionDE: 'Gratis Open-Air-Musikfestival in ganz Genf.', toddlerFriendly: true, free: true, url: '' },
  { id: 'ge-fetes-geneve', name: 'Fêtes de Genève', nameDE: 'Fêtes de Genève', city: 'geneva', startDate: '2026-08-06', endDate: '2026-08-15', description: "Geneva's biggest festival along the lake.", descriptionDE: 'Genfs grösstes Fest am See.', toddlerFriendly: true, free: true, url: '' },
  { id: 'ge-escalade', name: "L'Escalade", nameDE: "L'Escalade", city: 'geneva', startDate: '2026-12-11', endDate: '2026-12-13', description: "Geneva's iconic historical festival — costumed parade.", descriptionDE: 'Genfs ikonisches Geschichtsfest — Kostümumzug.', toddlerFriendly: true, free: true, url: '' },
  { id: 'ge-christmas', name: 'Geneva Christmas Market', nameDE: 'Genfer Weihnachtsmarkt', city: 'geneva', startDate: '2026-11-19', endDate: '2026-12-24', description: 'Christmas market on Quai du Mont-Blanc.', descriptionDE: 'Weihnachtsmarkt am Quai du Mont-Blanc.', toddlerFriendly: true, free: true, url: '' },
  { id: 'ge-jet-deau', name: "Jet d'Eau Season", nameDE: "Jet d'Eau Saison", city: 'geneva', startDate: '2026-03-01', endDate: '2026-10-31', description: "Geneva's famous 140m water fountain operates daily.", descriptionDE: 'Genfs berühmte 140m Wasserfontäne läuft täglich.', toddlerFriendly: true, free: true, url: '' },
  { id: 'ge-national-day', name: 'Swiss National Day Geneva', nameDE: '1. August Feier Genf', city: 'geneva', startDate: '2026-08-01', endDate: '2026-08-01', description: 'National Day fireworks over Lake Geneva.', descriptionDE: '1. August Feuerwerk über dem Genfersee.', toddlerFriendly: true, free: true, url: '' },

  // ═══ LAUSANNE ═══
  { id: 'la-fete-tulipe', name: 'Fête de la Tulipe', nameDE: 'Tulpenfest', city: 'lausanne', startDate: '2026-04-01', endDate: '2026-05-10', description: 'Tulip festival with 100,000+ blooming tulips.', descriptionDE: 'Tulpenfest mit über 100\'000 blühenden Tulpen.', toddlerFriendly: true, free: true, url: '' },
  { id: 'la-festival-cite', name: 'Festival de la Cité', nameDE: 'Festival de la Cité', city: 'lausanne', startDate: '2026-07-07', endDate: '2026-07-12', description: 'Free performing arts festival in the old town.', descriptionDE: 'Gratis Kulturfestival in der Altstadt.', toddlerFriendly: true, free: true, url: '' },
  { id: 'la-lausanne-lumieres', name: 'Lausanne Lumières', nameDE: 'Lausanne Lumières', city: 'lausanne', startDate: '2026-11-26', endDate: '2027-01-03', description: 'Winter light art festival.', descriptionDE: 'Winter-Lichtkunst-Festival.', toddlerFriendly: true, free: true, url: '' },
  { id: 'la-bo-noel', name: 'Bô Noël', nameDE: 'Bô Noël', city: 'lausanne', startDate: '2026-11-21', endDate: '2026-12-31', description: "Lausanne's Christmas festival with markets and ice rink.", descriptionDE: 'Lausannes Weihnachtsfest mit Märkten und Eisbahn.', toddlerFriendly: true, free: true, url: '' },
  { id: 'la-athletissima', name: 'Athletissima', nameDE: 'Athletissima', city: 'lausanne', startDate: '2026-08-27', endDate: '2026-08-27', description: 'World-class athletics meeting.', descriptionDE: 'Weltklasse-Leichtathletik-Meeting.', toddlerFriendly: true, free: false, url: '' },
  { id: 'la-national-day', name: 'Swiss National Day Lausanne', nameDE: '1. August Feier Lausanne', city: 'lausanne', startDate: '2026-08-01', endDate: '2026-08-01', description: 'National Day celebrations along the lakefront.', descriptionDE: '1. August Feier am Seeufer.', toddlerFriendly: true, free: true, url: '' },

  // ═══ LUZERN ═══
  { id: 'lu-lilu', name: 'LiLu Lichtfestival', nameDE: 'LiLu Lichtfestival', city: 'luzern', startDate: '2026-01-08', endDate: '2026-01-18', description: "Winter light festival illuminating Lucerne's old town.", descriptionDE: 'Winter-Lichtfestival in der Luzerner Altstadt.', toddlerFriendly: true, free: true, url: '' },
  { id: 'lu-fasnacht', name: 'Luzerner Fasnacht', nameDE: 'Luzerner Fasnacht', city: 'luzern', startDate: '2026-02-12', endDate: '2026-02-17', description: "Lucerne's famous carnival with Fritschi parade.", descriptionDE: 'Luzerns berühmte Fasnacht mit Fritschi-Umzug.', toddlerFriendly: true, free: true, url: '' },
  { id: 'lu-luzerner-fest', name: 'Luzerner Fest', nameDE: 'Luzerner Fest', city: 'luzern', startDate: '2026-06-27', endDate: '2026-06-27', description: 'City festival along the lake with fireworks.', descriptionDE: 'Stadtfest am See mit Feuerwerk.', toddlerFriendly: true, free: true, url: '' },
  { id: 'lu-blue-balls', name: 'Blue Balls Festival', nameDE: 'Blue Balls Festival', city: 'luzern', startDate: '2026-07-17', endDate: '2026-07-25', description: 'Music and art festival at the KKL.', descriptionDE: 'Musik- und Kunstfestival am KKL.', toddlerFriendly: false, free: false, url: '' },
  { id: 'lu-kaesefest', name: 'Käsefest', nameDE: 'Käsefest', city: 'luzern', startDate: '2026-09-05', endDate: '2026-09-05', description: 'Cheese festival with tastings and family activities.', descriptionDE: 'Käsefest mit Degustationen und Familienaktivitäten.', toddlerFriendly: true, free: true, url: '' },
  { id: 'lu-christmas', name: 'Lucerne Christmas Market', nameDE: 'Luzerner Weihnachtsmarkt', city: 'luzern', startDate: '2026-11-27', endDate: '2026-12-22', description: 'Christmas market in the Franciscan Church.', descriptionDE: 'Weihnachtsmarkt in der Franziskanerkirche.', toddlerFriendly: true, free: true, url: '' },
  { id: 'lu-circus-knie', name: 'Circus Knie Luzern', nameDE: 'Circus Knie Luzern', city: 'luzern', startDate: '2026-06-11', endDate: '2026-06-21', description: "Switzerland's national circus visits Lucerne.", descriptionDE: 'Schweizer Nationalzirkus gastiert in Luzern.', toddlerFriendly: true, free: false, url: 'https://www.knie.ch/' },
  { id: 'lu-national-day', name: 'Swiss National Day Lucerne', nameDE: '1. August Feier Luzern', city: 'luzern', startDate: '2026-08-01', endDate: '2026-08-01', description: 'National Day celebrations with fireworks on the lake.', descriptionDE: '1. August Feier mit Feuerwerk am See.', toddlerFriendly: true, free: true, url: '' },
  { id: 'lu-fumetto', name: 'Fumetto Comics Festival', nameDE: 'Fumetto Comix-Festival', city: 'luzern', startDate: '2026-03-21', endDate: '2026-03-29', description: 'International comics festival.', descriptionDE: 'Internationales Comix-Festival.', toddlerFriendly: true, free: false, url: '' },

  // ═══ WINTERTHUR ═══
  { id: 'wt-afro-pfingsten', name: 'Afro-Pfingsten', nameDE: 'Afro-Pfingsten', city: 'winterthur', startDate: '2026-05-22', endDate: '2026-05-25', description: 'African music and culture festival.', descriptionDE: 'Afrikanisches Musik- und Kulturfestival.', toddlerFriendly: true, free: true, url: '' },
  { id: 'wt-albanifest', name: 'Albanifest', nameDE: 'Albanifest', city: 'winterthur', startDate: '2026-06-26', endDate: '2026-06-28', description: "Winterthur's biggest city festival.", descriptionDE: 'Winterthurs grösstes Stadtfest.', toddlerFriendly: true, free: true, url: '' },
  { id: 'wt-musikfestwochen', name: 'Musikfestwochen', nameDE: 'Musikfestwochen', city: 'winterthur', startDate: '2026-08-11', endDate: '2026-08-23', description: 'Free open-air concerts in the old town.', descriptionDE: 'Kostenlose Open-Air-Konzerte in der Altstadt.', toddlerFriendly: true, free: true, url: '' },
  { id: 'wt-christmas', name: 'Winterthur Christmas Market', nameDE: 'Winterthurer Weihnachtsmarkt', city: 'winterthur', startDate: '2026-11-19', endDate: '2026-12-22', description: "Christmas market with children's program.", descriptionDE: 'Weihnachtsmarkt mit Kinderprogramm.', toddlerFriendly: true, free: true, url: '' },
  { id: 'wt-national-day', name: 'Swiss National Day Winterthur', nameDE: '1. August Feier Winterthur', city: 'winterthur', startDate: '2026-08-01', endDate: '2026-08-01', description: 'National Day celebrations with fireworks.', descriptionDE: '1. August Feier mit Feuerwerk.', toddlerFriendly: true, free: true, url: '' },
];

export function getCityEvents(cityId) {
  return ALL_EVENTS.filter(e => e.city === cityId);
}
