import SwiftUI
import UIKit

// MARK: - Gradient Presets

extension LinearGradient {
    static var brand: LinearGradient {
        LinearGradient(
            colors: [Color.znNavy, Color.znNavy], startPoint: .leading, endPoint: .trailing
        )
    }
}

// MARK: - ShapeStyle conformance (enables `.brand` shorthand in .foregroundStyle etc.)

extension ShapeStyle where Self == Color {
    static var brand: Color { Color.brand }
    static var brandDark: Color { Color.brandDark }
    static var googleStars: Color { Color.googleStars }
}

/// Znuni design system color palette — warm editorial tones with Light/Dark support via Asset Catalog.
/// Core tokens (znNavy, znTerracotta, znCream, znSurface, znBorder, znInk, znBody, znMuted,
/// znPositive, znNegative, znAlertBg, znInnerDivider, znNeutralTagBg, znNeutralTagText, znChevron)
/// are auto-generated by Xcode from the Asset Catalog color sets.
extension Color {
    // MARK: - Legacy Aliases (preserve .brand API across ~87 references)

    static var brand: Color { .znNavy }
    static var brandDark: Color { .znNavy }
    static var brandWarm: Color { .znTerracotta }
    static var appPrimary: Color { .znNavy }
    static var appAccent: Color { .znNavy }
    static var baseline: Color { .znNavy }

    // MARK: - Google Stars (amber #f59e0b)
    static let googleStars = Color(red: 0.961, green: 0.620, blue: 0.043)

    // MARK: - Semantic Colors

    static let positive = Color.znPositive
    static let negative = Color.znNegative
    static let amber = Color.znTerracotta
    static let weatherCard = Color.znNavy.opacity(0.06)

    // MARK: - Badge Colors

    static func badgeColor(for type: String) -> Color {
        switch type {
        case "green": return .znPositive
        case "red": return .znNegative
        case "blue": return .znNavy
        case "amber", "orange": return .znTerracotta
        case "yellow": return .znTerracotta.opacity(0.85)
        case "purple": return .znNavy.opacity(0.75)
        case "gray": return .znMuted
        default: return .znMuted
        }
    }

    // MARK: - Transport Status

    static func transportStatus(_ status: String) -> Color {
        switch status {
        case "none": return .znPositive
        case "minor": return .znTerracotta
        case "major": return .znNegative
        default: return .znMuted
        }
    }

    // MARK: - Sunshine Colors

    static func sunshineColor(hours: Double) -> Color {
        if hours > 6 { return .znTerracotta }
        if hours > 3 { return .znNavy.opacity(0.7) }
        return .znMuted
    }

    // MARK: - Snow Colors

    static func snowColor(cm: Double) -> Color {
        if cm > 30 { return .znNavy }
        if cm > 10 { return .znNavy.opacity(0.6) }
        return .znMuted
    }

    // MARK: - Sentiment

    static func sentimentColor(_ sentiment: String?) -> Color {
        switch sentiment {
        case "positive": return .znPositive
        case "negative": return .znNegative
        default: return .znMuted
        }
    }

    // MARK: - Category Colors

    static func categoryColor(_ key: String) -> Color {
        switch key {
        case "topStories": return .znNavy
        case "politics": return .znNavy.opacity(0.75)
        case "disruptions": return .znNegative
        case "events": return .znPositive
        case "culture": return .znTerracotta
        case "local": return .znTerracotta.opacity(0.7)
        default: return .znMuted
        }
    }

    // MARK: - Card Border Colors

    static func activityBorderColor(indoor: Bool, isFree: Bool) -> Color {
        if isFree { return .znPositive }
        return indoor ? .znNavy : .znTerracotta
    }

    static func cuisineBorderColor(_ category: String?) -> Color {
        switch category?.lowercased() {
        case "swiss": return .znNegative
        case "italian": return .znPositive
        case "asian": return .znTerracotta
        case "kebab": return .znTerracotta.opacity(0.7)
        case "cafe": return .znNavy.opacity(0.65)
        case "vegetarian": return .znPositive.opacity(0.8)
        case "fastfood": return .znTerracotta.opacity(0.85)
        default: return .znNavy
        }
    }
}

// MARK: - Spacing Constants

/// Znuni spacing scale for consistent layout.
enum AppSpacing {
    /// Card inner padding (16pt)
    static let cardPadding: CGFloat = 16
    /// Standard horizontal section padding
    static let sectionHorizontal: CGFloat = 16
    /// Vertical gap between cards in a list
    static let cardGap: CGFloat = 12
    /// Corner radius for cards (16pt)
    static let cardRadius: CGFloat = 16
    /// Left accent bar width on cards (3pt)
    static let borderStripWidth: CGFloat = 3
    /// Shadow radius for cards
    static let cardShadowRadius: CGFloat = 8
    /// Map height in inline views
    static let mapHeight: CGFloat = 280
    /// News hero banner height
    static let heroHeight: CGFloat = 220
    /// Mini map preview height
    static let miniMapHeight: CGFloat = 178
    /// News card corner radius
    static let newsCardRadius: CGFloat = 16
    /// Near-you chip card width
    static let nearYouChipWidth: CGFloat = 130
}

// MARK: - Shadow Tokens

/// Znuni shadow presets for visual hierarchy.
enum AppShadow {
    /// Primary card shadow
    static let card: (color: Color, radius: CGFloat, x: CGFloat, y: CGFloat) = (
        .black.opacity(0.08), 8, 0, 2
    )
    /// Subtle shadow — secondary/lightweight cards
    static let subtle: (color: Color, radius: CGFloat, x: CGFloat, y: CGFloat) = (
        .black.opacity(0.05), 4, 0, 2
    )
}

// MARK: - Animation Tokens

/// Standardised animation presets for consistent motion.
enum AppAnimation {
    static let standardEase: Animation = .easeInOut(duration: 0.2)
    static let expandEase: Animation = .easeInOut(duration: 0.3)
    static let spring: Animation = .spring(response: 0.3, dampingFraction: 0.7)
    static let selectedScale: CGFloat = 1.02
}

// MARK: - Card Style ViewModifier

/// Standard card styling: znSurface background, rounded corners, optional left accent bar.
struct CardStyle: ViewModifier {
    var borderColor: Color? = nil

    func body(content: Content) -> some View {
        content
            .background(Color.znSurface)
            .clipShape(RoundedRectangle(cornerRadius: AppSpacing.cardRadius))
            .overlay(alignment: .leading) {
                if let borderColor {
                    RoundedRectangle(cornerRadius: 1.5)
                        .fill(borderColor)
                        .frame(width: AppSpacing.borderStripWidth)
                        .padding(.vertical, 8)
                }
            }
            .shadow(color: AppShadow.card.color, radius: AppShadow.card.radius, x: AppShadow.card.x, y: AppShadow.card.y)
    }
}

/// Lighter card style for secondary cards.
struct SubtleCardStyle: ViewModifier {
    func body(content: Content) -> some View {
        content
            .background(Color.znSurface)
            .clipShape(RoundedRectangle(cornerRadius: AppSpacing.cardRadius))
            .shadow(color: AppShadow.subtle.color, radius: AppShadow.subtle.radius, x: AppShadow.subtle.x, y: AppShadow.subtle.y)
    }
}

extension View {
    func cardStyle(borderColor: Color? = nil) -> some View {
        modifier(CardStyle(borderColor: borderColor))
    }

    func subtleCardStyle() -> some View {
        modifier(SubtleCardStyle())
    }
}

// MARK: - Znuni Typography (Playfair serif headlines, system sans body)

extension Font {
    /// Display title — Playfair 32pt (hero titles)
    static var displayTitle: Font {
        .custom("Playfair", size: 32)
    }

    /// Section title — Playfair 22pt semibold
    static var sectionTitle: Font {
        .custom("Playfair", size: 22).weight(.semibold)
    }

    /// Card headline — Playfair 17pt semibold (card names/titles)
    static var cardHeadline: Font {
        .custom("Playfair", size: 17).weight(.semibold)
    }

    /// Card title — alias for cardHeadline
    static var cardTitle: Font {
        .custom("Playfair", size: 17).weight(.semibold)
    }

    /// Eyebrow text — system 11pt medium, uppercase with tracking
    static var znEyebrow: Font {
        .system(size: 11, weight: .medium)
    }

    /// Label text — system 12pt medium
    static var znLabel: Font {
        .system(size: 12, weight: .medium)
    }

    /// Mono numbers — for times, distances
    static var znMono: Font {
        .system(.caption, design: .monospaced).weight(.medium)
    }

    // MARK: - News & Explore Tokens

    /// Hero title — Playfair 30pt regular weight (matches mockup font-weight: 400)
    static var heroTitle: Font {
        .custom("Playfair", size: 30)
    }

    /// Hero temperature — system 40pt ultraLight
    static var heroTemperature: Font {
        .system(size: 40, weight: .ultraLight)
    }

    /// News card headline — Playfair 15pt semibold
    static var newsCardHeadline: Font {
        .custom("Playfair", size: 15).weight(.semibold)
    }

    /// Section headline — Playfair 22pt regular (matches mockup .section-heading)
    static var sectionHeadline: Font {
        .custom("Playfair", size: 22)
    }

    /// Category card title — Playfair 18pt semibold
    static var categoryCardTitle: Font {
        .custom("Playfair", size: 18).weight(.semibold)
    }
}
